org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8 -Dorg.sqlite.tmpdir=C:\\Users\\KvinMach\\AppData\\Local\\Temp\\voicehands-sqlite -Djava.io.tmpdir=C:\\Users\\KvinMach\\AppData\\Local\\Temp\\voicehands-sqlite
android.useAndroidX=true
android.nonTransitiveRClass=true
kotlin.code.style=official
android.defaults.buildfeatures.resvalues=true
android.sdk.defaultTargetSdkToCompileSdkIfUnset=false
android.enableAppCompileTimeRClass=false
android.usesSdkInManifest.disallowed=false
android.uniquePackageNames=false
android.dependency.useConstraints=true
android.r8.strictFullModeForKeepRules=false
android.r8.optimizedResourceShrinking=false
#android.builtInKotlin=false
#android.newDsl=false

# Room/KSP necesita un temp con permiso de ejecución; C:\WINDOWS\TEMP suele fallar en Windows.
systemProp.org.sqlite.tmpdir=C:\\Users\\KvinMach\\AppData\\Local\\Temp\\voicehands-sqlite
systemProp.java.io.tmpdir=C:\\Users\\KvinMach\\AppData\\Local\\Temp\\voicehands-sqlite

